apiVersion: apps/v1
kind: Deployment
metadata:
  name: forntend-deploy
  labels:
    app: forntend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-pod
  template:
    metadata:
      labels:
        app: my-pod
    spec:
      containers:
      - name: forntend
        image: sreelakshmi14/kanban-board_kanban-ui:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: DB_SERVER
          value: "kanban-postgres"
        - name: POSTGRES_DB
          value: "kanban"
        - name: POSTGRES_USER
          value: "kanban"
        - name: POSTGRES_PASSWORD
          value: "kanban"

        ports:
          - name: http
            containerPort: 80
      
